app = 'rss-lambda'
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = 'sjc'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[mounts]
source = "app_blobs"
destination = "/app/blobs"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
