# fly.toml app configuration file generated for rss-lambda on 2024-03-25T08:54:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rss-lambda'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
